#!/bin/bash

SRC="$1"; # must be xxx.cpp
OUT="${SRC%.*}";
ASM="$OUT.s";

if [ "$SRC" == "$OUT.cpp" ]; then
	G=g++
elif [ "$SRC" == "$OUT.c" ]; then
	G=gcc
else
	echo >&2 "This source has unknown extention ${SRC##*.}";
fi

echo -e "src:$SRC\nasm:$ASM\nout:$OUT";

if ! $G -S -o "$ASM" "$SRC"; then
	echo >&2 "This source has compiling error.";
	exit 1;
fi

if cat $ASM | grep -E '^#APP$' > /dev/null; then
	echo >&2 "This source uses asm.";
	exit 2;
fi

if ! cat $ASM | perl -ne 's/^.*?([a-zA-Z_][a-zA-Z_0-9]*)\@.*/$1/ && print' | c++filt | sort -u | ./checker-symbol > symbol-unknown; then
	echo >&2 "This source uses invalid external function.";
	exit 3;
fi

if ! g++ -o "$OUT" "$ASM"; then
	echo >&2 "This source has linking error.";
	exit 1;
fi