#!/bin/bash

function remove_cxx {
	local symbol;
	while read symbol; do
		if [ "$symbol" == "`c++filt $symbol`" ]; then
			echo $symbol;
		fi
	done
}

g++ -S gen.cpp -o - | perl -ne 's/^\tcall\t(.*?)\@PLT$/$1/ && print' | remove_cxx | sort -u -V -o symbol
